# Generated by Django 3.0.3 on 2020-02-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='articles/')),
                ('desc', models.TextField()),
                ('github_link', models.URLField()),
                ('deployed_link', models.URLField()),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('design', models.IntegerField(default=0)),
                ('usablity', models.IntegerField(default=0)),
                ('creativity', models.IntegerField(default=0)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            bases=('core.basemodel',),
        ),
    ]
